version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: ridetrip
      POSTGRES_DATABASE_DEFAULT: postgres
      JWT_PASSWORD: 74r8ohufgw7y8o
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm start

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
